name: Build FOV Tweak
on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Install Dependencies + SDK
        run: |
          brew install ldid
          rm -rf $HOME/theos/sdks
          git clone https://github.com/theos/sdks $HOME/theos/sdks

      - name: Build
        run: |
          export THEOS=$HOME/theos
          make

      - name: Upload dylib
        uses: actions/upload-artifact@v4
        with:
          name: SmashKartsFOV
          path: .theos/obj/debug/*.dylib
